# Docker environment for local development
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:3.2.2
    ports:
      - ${ZOOKEEPER_PORT}:2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

  kafka:
    image: confluentinc/cp-kafka:3.2.2
    ports:
      - ${KAFKA_PORT}:9092
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:${KAFKA_PORT}
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
